#/bin/bash

mv thomas-hardy_far-from-the-madding-crowd.azw3                                        "Thomas Hardy - Far From The Madding Crowd.azw3"
mv fergus-hume_the-mystery-of-a-hansom-cab.azw3                                        "Fergus Hume - The Mystery Of A Hansom Cab.azw3"
mv tom-taylor_our-american-cousin.azw3                                                 "Tom Taylor - Our American Cousin.azw3"
mv maurice-leblanc_the-golden-triangle.azw3                                            "Maurice Leblanc - The Golden Triangle.azw3"
mv h-g-wells_short-fiction.azw3                                                        "H G Wells - Short Fiction.azw3"
mv fyodor-dostoevsky_notes-from-underground.azw3                                       "Fyodor Dostoevsky - Notes From Underground.azw3"
mv luigi-pirandello_six-characters-in-search-of-an-author.azw3                         "Luigi Pirandello - Six Characters In Search Of An Author.azw3"
mv agatha-christie_the-murder-on-the-links.azw3                                        "Agatha Christie - The Murder On The Links.azw3"
mv fyodor-dostoevsky_the-brothers-karamazov.azw3                                       "Fyodor Dostoevsky - The Brothers Karamazov.azw3"
mv ludwig-wittgenstein_tractatus-logico-philosophicus.azw3                             "Ludwig Wittgenstein - Tractatus Logico Philosophicus.azw3"
mv george-bernard-shaw_major-barbara.azw3                                              "George Bernard Shaw - Major Barbara.azw3"
mv wilkie-collins_man-and-wife.azw3                                                    "Wilkie Collins - Man And Wife.azw3"
mv okakura-kakuzo_the-book-of-tea.azw3                                                 "Okakura Kakuzo - The Book Of Tea.azw3"
mv carey-rockwell_stand-by-for-mars.azw3                                               "Carey Rockwell - Stand By For Mars.azw3"
mv p-g-wodehouse_psmith-in-the-city.azw3                                               "P G Wodehouse - Psmith In The City.azw3"
mv ernest-shackleton_south.azw3                                                        "Ernest Shackleton - South.azw3"
mv charles-darwin_the-origin-of-species.azw3                                           "Charles Darwin - The Origin Of Species.azw3"
mv stephen-crane_the-red-badge-of-courage.azw3                                         "Stephen Crane - The Red Badge Of Courage.azw3"
mv jack-london_the-son-of-the-wolf.azw3                                                "Jack London - The Son Of The Wolf.azw3"
mv thomas-hardy_tess-of-the-durbervilles.azw3                                          "Thomas Hardy - Tess Of The Durbervilles.azw3"
mv maurice-leblanc_the-confessions-of-arsene-lupin.azw3                                "Maurice Leblanc - The Confessions Of Arsene Lupin.azw3"
mv fyodor-sologub_the-created-legend.azw3                                              "Fyodor Sologub - The Created Legend.azw3"
mv john-meade-falkner_moonfleet.azw3                                                   "John Meade Falkner - Moonfleet.azw3"
mv anthony-hope_the-prisoner-of-zenda.azw3                                             "Anthony Hope - The Prisoner Of Zenda.azw3"
mv baroness-orczy_the-scarlet-pimpernel.azw3                                           "Baroness Orczy - The Scarlet Pimpernel.azw3"
mv l-frank-baum_the-wonderful-wizard-of-oz.azw3                                        "L Frank Baum - The Wonderful Wizard Of Oz.azw3"
mv jane-austen_persuasion.azw3                                                         "Jane Austen - Persuasion.azw3"
mv aristotle_nicomachean-ethics.azw3                                                   "Aristotle - Nicomachean Ethics.azw3"
mv philip-francis-nowlan_the-airlords-of-han.azw3                                      "Philip Francis Nowlan - The Airlords Of Han.azw3"
mv ford-madox-ford_the-good-soldier.azw3                                               "Ford Madox Ford - The Good Soldier.azw3"
mv p-t-barnum_struggles-and-triumphs.azw3                                              "P T Barnum - Struggles And Triumphs.azw3"
mv virginia-woolf_the-voyage-out.azw3                                                  "Virginia Woolf - The Voyage Out.azw3"
mv andre-norton_star-hunter.azw3                                                       "Andre Norton - Star Hunter.azw3"
mv charles-dickens_hard-times.azw3                                                     "Charles Dickens - Hard Times.azw3"
mv grazia-deledda_after-the-divorce.azw3                                               "Grazia Deledda - After The Divorce.azw3"
mv andre-norton_voodoo-planet.azw3                                                     "Andre Norton - Voodoo Planet.azw3"
mv arthur-conan-doyle_his-last-bow.azw3                                                "Arthur Conan Doyle - His Last Bow.azw3"
mv lytton-strachey_eminent-victorians.azw3                                             "Lytton Strachey - Eminent Victorians.azw3"
mv camille-flammarion_omega.azw3                                                       "Camille Flammarion - Omega.azw3"
mv benjamin-disraeli_sybil.azw3                                                        "Benjamin Disraeli - Sybil.azw3"
mv fyodor-sologub_the-little-demon.azw3                                                "Fyodor Sologub - The Little Demon.azw3"
mv mark-twain_the-prince-and-the-pauper.azw3                                           "Mark Twain - The Prince And The Pauper.azw3"
mv maurice-leblanc_the-crystal-stopper.azw3                                            "Maurice Leblanc - The Crystal Stopper.azw3"
mv arthur-conan-doyle_the-return-of-sherlock-holmes.azw3                               "Arthur Conan Doyle - The Return Of Sherlock Holmes.azw3"
mv edith-wharton_the-house-of-mirth.azw3                                               "Edith Wharton - The House Of Mirth.azw3"
mv h-g-wells_kipps.azw3                                                                "H G Wells - Kipps.azw3"
mv arnold-bennett_the-grand-babylon-hotel.azw3                                         "Arnold Bennett - The Grand Babylon Hotel.azw3"
mv aesop_fables.azw3                                                                   "Aesop - Fables.azw3"
mv ulysses-s-grant_personal-memoirs-of-ulysses-s-grant.azw3                            "Ulysses S Grant - Personal Memoirs Of Ulysses S Grant.azw3"
mv emily-bronte_wuthering-heights.azw3                                                 "Emily Bronte - Wuthering Heights.azw3"
mv maurice-leblanc_813.azw3                                                            "Maurice Leblanc - 813.azw3"
mv kate-chopin_the-awakening.azw3                                                      "Kate Chopin - The Awakening.azw3"
mv thomas-hardy_the-woodlanders.azw3                                                   "Thomas Hardy - The Woodlanders.azw3"
mv j-m-barrie_the-little-white-bird.azw3                                               "J M Barrie - The Little White Bird.azw3"
mv arthur-conan-doyle_the-memoirs-of-sherlock-holmes.azw3                              "Arthur Conan Doyle - The Memoirs Of Sherlock Holmes.azw3"
mv auguste-comte_a-general-view-of-positivism.azw3                                     "Auguste Comte - A General View Of Positivism.azw3"
mv wilfred-owen_poetry.azw3                                                            "Wilfred Owen - Poetry.azw3"
mv e-nesbit_the-railway-children.azw3                                                  "E Nesbit - The Railway Children.azw3"
mv alexandre-dumas_the-black-tulip.azw3                                                "Alexandre Dumas - The Black Tulip.azw3"
mv arthur-conan-doyle_the-adventures-of-sherlock-holmes.azw3                           "Arthur Conan Doyle - The Adventures Of Sherlock Holmes.azw3"
mv h-g-wells_the-wonderful-visit.azw3                                                  "H G Wells - The Wonderful Visit.azw3"
mv walter-scott_ivanhoe.azw3                                                           "Walter Scott - Ivanhoe.azw3"
mv h-g-wells_the-history-of-mr-polly.azw3                                              "H G Wells - The History Of Mr Polly.azw3"
mv christopher-morley_the-haunted-bookshop.azw3                                        "Christopher Morley - The Haunted Bookshop.azw3"
mv maurice-leblanc_the-hollow-needle.azw3                                              "Maurice Leblanc - The Hollow Needle.azw3"
mv h-rider-haggard_king-solomons-mines.azw3                                            "H Rider Haggard - King Solomons Mines.azw3"
mv joseph-conrad_nostromo.azw3                                                         "Joseph Conrad - Nostromo.azw3"
mv robert-louis-stevenson_kidnapped.azw3                                               "Robert Louis Stevenson - Kidnapped.azw3"
mv e-phillips-oppenheim_the-great-impersonation.azw3                                   "E Phillips Oppenheim - The Great Impersonation.azw3"
mv jack-london_when-god-laughs.azw3                                                    "Jack London - When God Laughs.azw3"
mv khalil-gibran_the-forerunner.azw3                                                   "Khalil Gibran - The Forerunner.azw3"
mv charles-dickens_a-christmas-carol.azw3                                              "Charles Dickens - A Christmas Carol.azw3"
mv robert-e-howard_short-fiction.azw3                                                  "Robert E Howard - Short Fiction.azw3"
mv arthur-conan-doyle_the-sign-of-the-four.azw3                                        "Arthur Conan Doyle - The Sign Of The Four.azw3"
mv maurice-leblanc_arsene-lupin-versus-herlock-sholmes.azw3                            "Maurice Leblanc - Arsene Lupin Versus Herlock Sholmes.azw3"
mv arthur-conan-doyle_a-study-in-scarlet.azw3                                          "Arthur Conan Doyle - A Study In Scarlet.azw3"
mv h-p-lovecraft_short-fiction.azw3                                                    "H P Lovecraft - Short Fiction.azw3"
mv khalil-gibran_the-madman.azw3                                                       "Khalil Gibran - The Madman.azw3"
mv e-nesbit_the-enchanted-castle.azw3                                                  "E Nesbit - The Enchanted Castle.azw3"
mv w-somerset-maugham_of-human-bondage.azw3                                            "W Somerset Maugham - Of Human Bondage.azw3"
mv rudyard-kipling_just-so-stories.azw3                                                "Rudyard Kipling - Just So Stories.azw3"
mv maurice-leblanc_the-extraordinary-adventures-of-arsene-lupin-gentleman-burglar.azw3 "Maurice Leblanc - The Extraordinary Adventures Of Arsene Lupin Gentleman Burglar.azw3"
mv herman-melville_moby-dick.azw3                                                      "Herman Melville - Moby Dick.azw3"
mv e-pauline-johnson_legends-of-vancouver.azw3                                         "E Pauline Johnson - Legends Of Vancouver.azw3"
mv selma-lagerlof_the-story-of-gosta-berling.azw3                                      "Selma Lagerlof - The Story Of Gosta Berling.azw3"
mv jane-austen_emma.azw3                                                               "Jane Austen - Emma.azw3"
mv august-strindberg_the-inferno.azw3                                                  "August Strindberg - The Inferno.azw3"
mv gertrude-stein_three-lives.azw3                                                     "Gertrude Stein - Three Lives.azw3"
mv washington-irving_the-sketch-book-of-geoffrey-crayon-gent.azw3                      "Washington Irving - The Sketch Book Of Geoffrey Crayon Gent.azw3"
mv anthony-trollope_barchester-towers.azw3                                             "Anthony Trollope - Barchester Towers.azw3"
mv anthony-trollope_the-warden.azw3                                                    "Anthony Trollope - The Warden.azw3"
mv vsevolod-garshin_short-fiction.azw3                                                 "Vsevolod Garshin - Short Fiction.azw3"
mv george-macdonald_phantastes.azw3                                                    "George Macdonald - Phantastes.azw3"
mv henry-david-thoreau_a-yankee-in-canada.azw3                                         "Henry David Thoreau - A Yankee In Canada.azw3"
mv edwin-a-abbott_flatland.azw3                                                        "Edwin A Abbott - Flatland.azw3"
mv john-buchan_the-thirty-nine-steps.azw3                                              "John Buchan - The Thirty Nine Steps.azw3"
mv j-sheridan-le-fanu_in-a-glass-darkly.azw3                                           "J Sheridan Le Fanu - In A Glass Darkly.azw3"
mv arthur-conan-doyle_the-hound-of-the-baskervilles.azw3                               "Arthur Conan Doyle - The Hound Of The Baskervilles.azw3"
mv f-scott-fitzgerald_this-side-of-paradise.azw3                                       "F Scott Fitzgerald - This Side Of Paradise.azw3"
mv thomas-love-peacock_nightmare-abbey.azw3                                            "Thomas Love Peacock - Nightmare Abbey.azw3"
mv nikolai-gogol_short-fiction.azw3                                                    "Nikolai Gogol - Short Fiction.azw3"
mv p-g-wodehouse_love-among-the-chickens.azw3                                          "P G Wodehouse - Love Among The Chickens.azw3"
mv daniel-defoe_the-life-and-adventures-of-robinson-crusoe.azw3                        "Daniel Defoe - The Life And Adventures Of Robinson Crusoe.azw3"
mv j-sheridan-le-fanu_uncle-silas.azw3                                                 "J Sheridan Le Fanu - Uncle Silas.azw3"
mv elizabeth-barrett-browning_sonnets-from-the-portuguese.azw3                         "Elizabeth Barrett Browning - Sonnets From The Portuguese.azw3"
mv wilkie-collins_the-moonstone.azw3                                                   "Wilkie Collins - The Moonstone.azw3"
mv max-beerbohm_the-works-of-max-beerbohm.azw3                                         "Max Beerbohm - The Works Of Max Beerbohm.azw3"
mv j-m-barrie_peter-and-wendy.azw3                                                     "J M Barrie - Peter And Wendy.azw3"
mv rafael-sabatini_captain-blood.azw3                                                  "Rafael Sabatini - Captain Blood.azw3"
mv charles-dickens_bleak-house.azw3                                                    "Charles Dickens - Bleak House.azw3"
mv christopher-morley_parnassus-on-wheels.azw3                                         "Christopher Morley - Parnassus On Wheels.azw3"
mv lewis-carroll_through-the-looking-glass.azw3                                        "Lewis Carroll - Through The Looking Glass.azw3"
mv freeman-wills-crofts_the-pit-prop-syndicate.azw3                                    "Freeman Wills Crofts - The Pit Prop Syndicate.azw3"
mv john-keats_poetry.azw3                                                              "John Keats - Poetry.azw3"
mv rudyard-kipling_kim.azw3                                                            "Rudyard Kipling - Kim.azw3"
mv h-g-wells_the-island-of-doctor-moreau.azw3                                          "H G Wells - The Island Of Doctor Moreau.azw3"
mv karl-marx_friedrich-engels_the-communist-manifesto.azw3                             "Karl Marx - Friedrich Engels - The Communist Manifesto.azw3"
mv george-eliot_silas-marner.azw3                                                      "George Eliot - Silas Marner.azw3"
mv h-g-wells_the-invisible-man.azw3                                                    "H G Wells - The Invisible Man.azw3"
mv p-g-wodehouse_something-new.azw3                                                    "P G Wodehouse - Something New.azw3"
mv booth-tarkington_alice-adams.azw3                                                   "Booth Tarkington - Alice Adams.azw3"
mv t-s-eliot_poetry.azw3                                                               "T S Eliot - Poetry.azw3"
mv wilkie-collins_the-woman-in-white.azw3                                              "Wilkie Collins - The Woman In White.azw3"
mv g-k-chesterton_the-wisdom-of-father-brown.azw3                                      "G K Chesterton - The Wisdom Of Father Brown.azw3"
mv fyodor-dostoevsky_crime-and-punishment.azw3                                         "Fyodor Dostoevsky - Crime And Punishment.azw3"
mv wilkie-collins_no-name.azw3                                                         "Wilkie Collins - No Name.azw3"
mv william-makepeace-thackeray_vanity-fair.azw3                                        "William Makepeace Thackeray - Vanity Fair.azw3"
mv e-t-a-hoffmann_master-flea.azw3                                                     "E T A Hoffmann - Master Flea.azw3"
mv h-beam-piper_little-fuzzy.azw3                                                      "H Beam Piper - Little Fuzzy.azw3"
mv j-w-von-goethe_the-sorrows-of-young-werther.azw3                                    "J W Von Goethe - The Sorrows Of Young Werther.azw3"
mv erskine-childers_the-riddle-of-the-sands.azw3                                       "Erskine Childers - The Riddle Of The Sands.azw3"
mv august-strindberg_the-red-room.azw3                                                 "August Strindberg - The Red Room.azw3"
mv h-beam-piper_the-cosmic-computer.azw3                                               "H Beam Piper - The Cosmic Computer.azw3"
mv selma-lagerlof_the-wonderful-adventures-of-nils.azw3                                "Selma Lagerlof - The Wonderful Adventures Of Nils.azw3"
mv jack-london_lost-face.azw3                                                          "Jack London - Lost Face.azw3"
mv rabindranath-tagore_gitanjali.azw3                                                  "Rabindranath Tagore - Gitanjali.azw3"
mv booth-tarkington_the-magnificent-ambersons.azw3                                     "Booth Tarkington - The Magnificent Ambersons.azw3"
mv rafael-sabatini_scaramouche.azw3                                                    "Rafael Sabatini - Scaramouche.azw3"
mv thomas-carlyle_sartor-resartus.azw3                                                 "Thomas Carlyle - Sartor Resartus.azw3"
mv e-m-forster_a-room-with-a-view.azw3                                                 "E M Forster - A Room With A View.azw3"
mv nikolai-gogol_dead-souls.azw3                                                       "Nikolai Gogol - Dead Souls.azw3"
mv d-h-lawrence_sons-and-lovers.azw3                                                   "D H Lawrence - Sons And Lovers.azw3"
mv max-beerbohm_zuleika-dobson.azw3                                                    "Max Beerbohm - Zuleika Dobson.azw3"
mv james-de-mille_a-strange-manuscript-found-in-a-copper-cylinder.azw3                 "James De Mille - A Strange Manuscript Found In A Copper Cylinder.azw3"
mv francisco-de-quevedo_pablo-de-segovia-the-spanish-sharper.azw3                      "Francisco De Quevedo - Pablo De Segovia The Spanish Sharper.azw3"
mv john-stuart-mill_on-liberty.azw3                                                    "John Stuart Mill - On Liberty.azw3"
mv ethel-voynich_the-gadfly.azw3                                                       "Ethel Voynich - The Gadfly.azw3"
mv philip-francis-nowlan_armageddon-2419-a-d.azw3                                      "Philip Francis Nowlan - Armageddon 2419 A D.azw3"
mv george-meredith_the-shaving-of-shagpat.azw3                                         "George Meredith - The Shaving Of Shagpat.azw3"
mv agatha-christie_the-secret-adversary.azw3                                           "Agatha Christie - The Secret Adversary.azw3"
mv horace-walpole_the-castle-of-otranto.azw3                                           "Horace Walpole - The Castle Of Otranto.azw3"
mv william-hazlitt_table-talk.azw3                                                     "William Hazlitt - Table Talk.azw3"
mv f-marion-crawford_khaled-a-tale-of-arabia.azw3                                      "F Marion Crawford - Khaled A Tale Of Arabia.azw3"
mv george-macdonald_the-princess-and-the-goblin.azw3                                   "George Macdonald - The Princess And The Goblin.azw3"
mv g-k-chesterton_the-napoleon-of-notting-hill.azw3                                    "G K Chesterton - The Napoleon Of Notting Hill.azw3"
mv c-j-cutcliffe-hyne_the-lost-continent.azw3                                          "C J Cutcliffe Hyne - The Lost Continent.azw3"
mv joseph-conrad_the-secret-agent.azw3                                                 "Joseph Conrad - The Secret Agent.azw3"
mv robert-w-chambers_the-king-in-yellow.azw3                                           "Robert W Chambers - The King In Yellow.azw3"
mv william-morris_the-wood-beyond-the-world.azw3                                       "William Morris - The Wood Beyond The World.azw3"
mv william-hope-hodgson_the-house-on-the-borderland.azw3                               "William Hope Hodgson - The House On The Borderland.azw3"
mv david-lindsay_a-voyage-to-arcturus.azw3                                             "David Lindsay - A Voyage To Arcturus.azw3"
mv william-wollaston_the-religion-of-nature-delineated.azw3                            "William Wollaston - The Religion Of Nature Delineated.azw3"
mv benjamin-franklin_the-autobiography-of-benjamin-franklin.azw3                       "Benjamin Franklin - The Autobiography Of Benjamin Franklin.azw3"
mv leo-tolstoy_the-kingdom-of-god-is-within-you.azw3                                   "Leo Tolstoy - The Kingdom Of God Is Within You.azw3"
mv thomas-de-quincey_suspiria-de-profundis.azw3                                        "Thomas De Quincey - Suspiria De Profundis.azw3"
mv abraham-merritt_the-moon-pool.azw3                                                  "Abraham Merritt - The Moon Pool.azw3"
mv emile-zola_his-masterpiece.azw3                                                     "Emile Zola - His Masterpiece.azw3"
mv frances-hodgson-burnett_the-secret-garden.azw3                                      "Frances Hodgson Burnett - The Secret Garden.azw3"
mv daniel-defoe_a-journal-of-the-plague-year.azw3                                      "Daniel Defoe - A Journal Of The Plague Year.azw3"
mv jules-verne_the-mysterious-island.azw3                                              "Jules Verne - The Mysterious Island.azw3"
mv elizabeth-gaskell_cranford.azw3                                                     "Elizabeth Gaskell - Cranford.azw3"
mv seneca_dialogues.azw3                                                               "Seneca - Dialogues.azw3"
mv sax-rohmer_the-insidious-dr-fu-manchu.azw3                                          "Sax Rohmer - The Insidious Dr Fu Manchu.azw3"
mv honore-de-balzac_father-goriot.azw3                                                 "Honore De Balzac - Father Goriot.azw3"
mv rudyard-kipling_the-jungle-book.azw3                                                "Rudyard Kipling - The Jungle Book.azw3"
mv p-t-barnum_the-art-of-money-getting.azw3                                            "P T Barnum - The Art Of Money Getting.azw3"
mv samuel-johnson_the-history-of-rasselas-prince-of-abyssinia.azw3                     "Samuel Johnson - The History Of Rasselas Prince Of Abyssinia.azw3"
mv louisa-may-alcott_little-women.azw3                                                 "Louisa May Alcott - Little Women.azw3"
mv g-k-chesterton_the-innocence-of-father-brown.azw3                                   "G K Chesterton - The Innocence Of Father Brown.azw3"
mv h-g-wells_the-war-of-the-worlds.azw3                                                "H G Wells - The War Of The Worlds.azw3"
mv william-makepeace-thackeray_the-luck-of-barry-lyndon.azw3                           "William Makepeace Thackeray - The Luck Of Barry Lyndon.azw3"
mv jerome-k-jerome_three-men-in-a-boat.azw3                                            "Jerome K Jerome - Three Men In A Boat.azw3"
mv miguel-de-cervantes-saavedra_don-quixote.azw3                                       "Miguel De Cervantes Saavedra - Don Quixote.azw3"
mv h-beam-piper_space-viking.azw3                                                      "H Beam Piper - Space Viking.azw3"
mv p-g-wodehouse_right-ho-jeeves.azw3                                                  "P G Wodehouse - Right Ho Jeeves.azw3"
mv gustave-flaubert_madame-bovary.azw3                                                 "Gustave Flaubert - Madame Bovary.azw3"
mv james-fenimore-cooper_the-last-of-the-mohicans.azw3                                 "James Fenimore Cooper - The Last Of The Mohicans.azw3"
mv g-k-chesterton_the-man-who-was-thursday.azw3                                        "G K Chesterton - The Man Who Was Thursday.azw3"
mv philip-k-dick_short-fiction.azw3                                                    "Philip K Dick - Short Fiction.azw3"
mv leo-tolstoy_a-confession.azw3                                                       "Leo Tolstoy - A Confession.azw3"
mv algis-budrys_short-fiction.azw3                                                     "Algis Budrys - Short Fiction.azw3"
mv fritz-leiber_the-big-time.azw3                                                      "Fritz Leiber - The Big Time.azw3"
mv lord-dunsany_the-gods-of-pegana.azw3                                                "Lord Dunsany - The Gods Of Pegana.azw3"
mv kenneth-grahame_the-wind-in-the-willows.azw3                                        "Kenneth Grahame - The Wind In The Willows.azw3"
mv arthur-machen_short-fiction.azw3                                                    "Arthur Machen - Short Fiction.azw3"
mv anton-chekhov_the-duel.azw3                                                         "Anton Chekhov - The Duel.azw3"
mv mark-twain_a-connecticut-yankee-in-king-arthurs-court.azw3                          "Mark Twain - A Connecticut Yankee In King Arthurs Court.azw3"
mv arthur-conan-doyle_the-lost-world.azw3                                              "Arthur Conan Doyle - The Lost World.azw3"
mv charles-dickens_david-copperfield.azw3                                              "Charles Dickens - David Copperfield.azw3"
mv hermann-hesse_siddhartha.azw3                                                       "Hermann Hesse - Siddhartha.azw3"
mv mark-twain_the-adventures-of-huckleberry-finn.azw3                                  "Mark Twain - The Adventures Of Huckleberry Finn.azw3"
mv stanley-g-weinbaum_short-fiction.azw3                                               "Stanley G Weinbaum - Short Fiction.azw3"
mv robert-louis-stevenson_the-strange-case-of-dr-jekyll-and-mr-hyde.azw3               "Robert Louis Stevenson - The Strange Case Of Dr Jekyll And Mr Hyde.azw3"
mv mary-shelley_frankenstein.azw3                                                      "Mary Shelley - Frankenstein.azw3"
mv robert-louis-stevenson_treasure-island.azw3                                         "Robert Louis Stevenson - Treasure Island.azw3"
mv marcus-aurelius_meditations.azw3                                                    "Marcus Aurelius - Meditations.azw3"
mv william-wordsworth_samuel-taylor-coleridge_lyrical-ballads.azw3                     "William Wordsworth - Samuel Taylor Coleridge - Lyrical Ballads.azw3"
mv rudolph-erich-raspe_the-surprising-adventures-of-baron-munchausen.azw3              "Rudolph Erich Raspe - The Surprising Adventures Of Baron Munchausen.azw3"
mv apsley-cherry-garrard_the-worst-journey-in-the-world.azw3                           "Apsley Cherry Garrard - The Worst Journey In The World.azw3"
mv alfred-lord-tennyson_idylls-of-the-king.azw3                                        "Alfred Lord Tennyson - Idylls Of The King.azw3"
mv lewis-carroll_alices-adventures-in-wonderland.azw3                                  "Lewis Carroll - Alices Adventures In Wonderland.azw3"
mv edgar-rice-burroughs_a-princess-of-mars.azw3                                        "Edgar Rice Burroughs - A Princess Of Mars.azw3"
mv jules-verne_around-the-world-in-eighty-days.azw3                                    "Jules Verne - Around The World In Eighty Days.azw3"
mv upton-sinclair_the-jungle.azw3                                                      "Upton Sinclair - The Jungle.azw3"
mv jules-verne_twenty-thousand-leagues-under-the-seas.azw3                             "Jules Verne - Twenty Thousand Leagues Under The Seas.azw3"
mv jane-austen_pride-and-prejudice.azw3                                                "Jane Austen - Pride And Prejudice.azw3"
mv omar-khayyam_the-rubaiyat-of-omar-khayyam.azw3                                      "Omar Khayyam - The Rubaiyat Of Omar Khayyam.azw3"
mv henry-david-thoreau_walden.azw3                                                     "Henry David Thoreau - Walden.azw3"
mv robert-frost_north-of-boston.azw3                                                   "Robert Frost - North Of Boston.azw3"
mv anton-chekhov_short-fiction.azw3                                                    "Anton Chekhov - Short Fiction.azw3"
mv epictetus_the-enchiridion.azw3                                                      "Epictetus - The Enchiridion.azw3"
mv james-joyce_dubliners.azw3                                                          "James Joyce - Dubliners.azw3"
mv niccolo-machiavelli_the-prince.azw3                                                 "Niccolo Machiavelli - The Prince.azw3"
mv oscar-wilde_the-importance-of-being-earnest.azw3                                    "Oscar Wilde - The Importance Of Being Earnest.azw3"
mv oscar-wilde_the-picture-of-dorian-gray.azw3                                         "Oscar Wilde - The Picture Of Dorian Gray.azw3"
mv henry-james_the-turn-of-the-screw.azw3                                              "Henry James - The Turn Of The Screw.azw3"
mv bram-stoker_dracula.azw3                                                            "Bram Stoker - Dracula.azw3"
mv laozi_tao-te-ching.azw3                                                             "Laozi - Tao Te Ching.azw3"
mv thomas-de-quincey_confessions-of-an-english-opium-eater.azw3                        "Thomas De Quincey - Confessions Of An English Opium Eater.azw3"
mv edgar-allan-poe_the-narrative-of-arthur-gordon-pym-of-nantucket.azw3                "Edgar Allan Poe - The Narrative Of Arthur Gordon Pym Of Nantucket.azw3"
mv jack-london_white-fang.azw3                                                         "Jack London - White Fang.azw3"
mv agatha-christie_the-mysterious-affair-at-styles.azw3                                "Agatha Christie - The Mysterious Affair At Styles.azw3"
mv jack-london_the-call-of-the-wild.azw3                                               "Jack London - The Call Of The Wild.azw3"
mv friedrich-nietzsche_beyond-good-and-evil.azw3                                       "Friedrich Nietzsche - Beyond Good And Evil.azw3"
mv lord-dunsany_the-book-of-wonder.azw3                                                "Lord Dunsany - The Book Of Wonder.azw3"
mv joseph-conrad_heart-of-darkness.azw3                                                "Joseph Conrad - Heart Of Darkness.azw3"
mv voltaire_candide.azw3                                                               "Voltaire - Candide.azw3"
mv w-w-jacobs_the-lady-of-the-barge.azw3                                               "W W Jacobs - The Lady Of The Barge.azw3"
mv h-g-wells_the-time-machine.azw3                                                     "H G Wells - The Time Machine.azw3"
